name: FlexoAPP CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '18.x'

jobs:
  # Backend Tests
  backend-test:
    runs-on: ubuntu-latest
    name: Backend Tests (.NET Core)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore backend/
    
    - name: Build
      run: dotnet build backend/ --no-restore
    
    - name: Test
      run: dotnet test backend/ --no-build --verbosity normal

  # Frontend Tests  
  frontend-test:
    runs-on: ubuntu-latest
    name: Frontend Tests (Angular)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint
      run: |
        cd frontend  
        npm run lint
    
    - name: Test
      run: |
        cd frontend
        npm run test:ci
    
    - name: Build
      run: |
        cd frontend
        npm run build:prod

  # Docker Build
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build & Push
    needs: [backend-test, frontend-test]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          emiliolp1818/flexoapp:latest
          emiliolp1818/flexoapp:${{ github.sha }}